Repository CodingGrounds/INFO-3103-Final-Project, pull requests merged in 2020-03, with the labels that each got.

#13 Add RAML files
  raml/api.html
  raml/api.raml
  raml/responses/401.json
  raml/responses/403.json
  raml/responses/404.json
  raml/responses/409.json
Labels: documentation

#16 Create LDAP helper
  requirements.txt
  src/rickbox/app_config.py
  src/rickbox/database/database_helper.py
  src/rickbox/ldap/ldap_helper.py
Labels: backend, enhancement

#14 Initialize DB script & scripts folder
  scripts/db/bootstrap_db.sh
  scripts/db/procs/files.sql
  scripts/db/procs/folders.sql
  scripts/db/procs/users.sql
  scripts/db/schema/files.sql
  scripts/db/schema/fks.sql
  scripts/db/schema/folders.sql
  scripts/db/schema/indexes.sql
  scripts/db/schema/users.sql
  src/rickbox/database/schema.sql
  src/rickbox/database/sql/procs/add_file.sql
  src/rickbox/database/sql/procs/add_folder.sql
  src/rickbox/database/sql/procs/delete_file.sql
  src/rickbox/database/sql/schema/create_files.sql
  src/rickbox/database/sql/schema/create_fks.sql
  src/rickbox/database/sql/schema/create_folders.sql
  src/rickbox/database/sql/schema/create_indexes.sql
  src/rickbox/database/sql/schema/create_users.sql
Labels: backend

#15 Rework Schema
  scripts/db/bootstrapdb.sh
  scripts/db/procs/files.sql
  scripts/db/procs/users.sql
  scripts/db/schema/files.sql
  scripts/db/schema/fks.sql
  scripts/db/schema/indexes.sql
  scripts/db/schema/users.sql
Labels: backend, enhancement

#17 Link stored procedures to Python – pt1: users
  scripts/db/procs/users.sql
  src/rickbox/database/database_helper.py
  src/rickbox/database/models/user.py
  src/rickbox/util/validators.py
Labels: backend, enhancement

#18 Create User endpoints for logging in/out
  .gitignore
  requirements.txt
  src/rickbox/app.py
  src/rickbox/app_config.py
  src/rickbox/database/models/user.py
  src/rickbox/ldap/ldap_helper.py
  src/rickbox/resources/user_manager.py
  src/rickbox/resources/user_session.py
  src/rickbox/util/decorators.py
  src/rickbox/util/errors.py
Labels: backend, enhancement

#19 File endpoints
  .gitignore
  scripts/db/procs/files.sql
  src/rickbox/app.py
  src/rickbox/app_config.py
  src/rickbox/database/models/file.py
  src/rickbox/resources/file_collection_manager.py
  src/rickbox/resources/file_manager.py
  src/rickbox/resources/session_manager.py
  src/rickbox/resources/user_manager.py
  src/rickbox/util/decorators.py
  src/rickbox/util/errors.py
  src/rickbox/util/responses.py
Labels: backend, enhancement

#20 https-ify – lol checking in the private key
  src/rickbox/app.py
  src/rickbox/cert.pem
  src/rickbox/key.pem
  src/rickbox/resources/file_collection_manager.py
  src/rickbox/resources/file_manager.py
  src/rickbox/resources/session_manager.py
  src/rickbox/resources/user_manager.py
Labels: backend, enhancement

#21 Curl scripts to hit endpoints
  scripts/curl/app_config
  scripts/curl/automated/file.jpg
  scripts/curl/automated/run_tests
  scripts/curl/interactive/delete_file
  scripts/curl/interactive/download_file
  scripts/curl/interactive/get_user_details
  scripts/curl/interactive/is_logged_in
  scripts/curl/interactive/list_user_files
  scripts/curl/interactive/login
  scripts/curl/interactive/logout
  scripts/curl/interactive/rename_file
  scripts/curl/interactive/upload_file
  scripts/curl/lib
  scripts/db/procs/files.sql
  src/rickbox/database/models/file.py
  src/rickbox/resources/file_collection_manager.py
  src/rickbox/resources/file_manager.py
  src/rickbox/util/decorators.py
  src/rickbox/util/responses.py
Labels: backend, enhancement

#22 Fix the rename_file script
  README.md
  scripts/curl/interactive/rename_file
Labels: backend, bug

#23 Fix ModuleNotFoundError in ldap
  src/rickbox/ldap/__init__.py
Labels: backend, bug
